#docker-compose.ymlのバージョン
version: '3'
#docker volumeの設定
volumes:
  docker-volume:

#services以下に各コンテナの設定を書く
services:
  #Webサーバーのコンテナ
  web:
    image: nginx:1.18
    ports:
    - '8003:80'
    volumes:
    - ./server:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  #アプリケーションのコンテナ
  php:
    build: ./docker/php
    volumes:
    - ./server:/var/www

  #データベースのコンテナ
  db:
    image: mysql:5.7
    ports:
    - '23306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
    - docker-volume:/var/lib/mysql